---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark-updater
  namespace: isc-shared
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: benchmark-updater
  namespace: isc-shared
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - benchmark-data
    verbs:
      - get
      - list
      - create
      - update
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: benchmark-updater
  namespace: isc-shared
subjects:
  - kind: ServiceAccount
    name: benchmark-updater
    apiGroup: ""
roleRef:
  kind: Role
  name: benchmark-updater
  apiGroup: ""
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fedrampdata
  namespace: isc-shared
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fedrampread
              image: quay.io/jaosorior/fedrampread:latest
              serviceAccount: benchmark-updater
              imagePullPolicy: Always
              securityContext:
                readOnlyRootFileSystem: true
              command:
                - /bin/sh
                - -c
                - |-
                  set -eux;
                  date;
                  /usr/bin/fedrampread.py --product=ocp4 --jira-username=jhrozek.jirabot --jira-password-env=JIRA_PASS --jira-epic=CMP-888 --output json /cache/moderate.json;
                  kubectl create configmap benchmark-data --from-file=moderate.json=/cache/moderate.json --dry-run=client -o yaml | kubectl apply -f -;
              volumeMounts:
                - mountPath: /cache
                  name: cache-volume
              env:
                - name: JIRA_PASS
                  valueFrom:
                    secretKeyRef:
                      name: jira-secret
                      key: pass
          restartPolicy: OnFailure
          volumes:
            - name: cache-volume
              emptyDir: {}
